
package vista.factura;

import controlador.FacturaController;
import controlador.MetodoPagoController;
import java.util.List;
import modelo.entidades.Cliente;
import modelo.entidades.Factura;
import modelo.entidades.MetodoPago;
import vista.cliente.ClienteTableComboModel;
import vista.metodo_pago.MetodoPagoModel;

public class FacturaViewImpl extends javax.swing.JPanel implements FacturaView {
    
    private FacturaController fController;
    private MetodoPagoController mController;
    private FacturaTableModel facturaTableModel;
    private ClienteTableComboModel clienteTableModel;
    private MetodoPagoModel metodoPagoModel;
    private FacturaViewImplInternal panelFactura;

    /**
     * Creates new form FacturaViewImpl
     */
    public FacturaViewImpl() {
        facturaTableModel = new FacturaTableModel();
        clienteTableModel = ClienteTableComboModel.getInstance();
        metodoPagoModel = new MetodoPagoModel();
        initComponents();
        
        panelFactura = new FacturaViewImplInternal(this);
        jPanelFactura.add(panelFactura);
    }

    @Override
    public FacturaController getfController() {
        return fController;
    }

    @Override
    public MetodoPagoController getmController() {
        return mController;
    }

    @Override
    public void setfController(FacturaController fController) {
        this.fController = fController;
    }

    @Override
    public void setmController(MetodoPagoController mController) {
        this.mController = mController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFacturas = new javax.swing.JTable();
        jPanelFactura = new javax.swing.JPanel();
        jComboBoxMetodosPago = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonQuitarFiltro = new javax.swing.JButton();

        jTableFacturas.setModel(facturaTableModel);
        jTableFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFacturas);

        jPanelFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFactura.setLayout(new javax.swing.BoxLayout(jPanelFactura, javax.swing.BoxLayout.LINE_AXIS));

        jComboBoxMetodosPago.setModel(metodoPagoModel);

        jLabel1.setText("Métodos:");

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setActionCommand("Filter");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonQuitarFiltro.setText("Quitar Filtro");
        jButtonQuitarFiltro.setActionCommand("RemoveFilter");
        jButtonQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxMetodosPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButtonFiltrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonQuitarFiltro)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxMetodosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFiltrar)
                            .addComponent(jButtonQuitarFiltro))))
                .addGap(18, 18, 18)
                .addComponent(jPanelFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFacturasMouseClicked
        FacturaTableModel ftm = (FacturaTableModel) this.jTableFacturas.getModel();
        Factura factura = ftm.getFactura(this.jTableFacturas.getSelectedRow());
        
        panelFactura.setFactura(factura);
    }//GEN-LAST:event_jTableFacturasMouseClicked

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        MetodoPago metodoSelected = (MetodoPago) jComboBoxMetodosPago.getSelectedItem();
        List<Factura> facturas = fController.listarFacturasPorMetodoGesture(metodoSelected);
        
        facturaTableModel.setFacturas(facturas);
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonRemoveFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFilterActionPerformed
        jComboBoxMetodosPago.setSelectedItem(null);
        dataModelChanged();
    }//GEN-LAST:event_jButtonRemoveFilterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonQuitarFiltro;
    private javax.swing.JComboBox jComboBoxMetodosPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFacturas;
    // End of variables declaration//GEN-END:variables

    public ClienteTableComboModel getClienteTableModel() {
        return clienteTableModel;
    }
    
    public void fireCrearFacturaGesture(String identificador, Cliente cliente, String importe) {
        fController.crearFacturaGesture(identificador, cliente, Double.valueOf(importe));
    }
    
    public void fireModificarFacturaGesture(String identificador, Cliente cliente, String importe) {
        fController.modificarFacturaGesture(identificador, cliente, Double.valueOf(importe));
    }
    
    public void fireEliminarFacturaGesture(String identificador) {
        fController.eliminarFacturaGesture(identificador);
    }
    
    @Override
    public void dataModelChanged() {
        facturaTableModel.setFacturas(fController.listarFacturasGesture());
        metodoPagoModel.setMetodos(mController.listarMetodosGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                dataModelChanged();
            }
        });
    }
    
}
