
package vista.cliente;

import controlador.ClienteController;
import modelo.entidades.Cliente;

public class ClienteViewImpl extends javax.swing.JPanel implements ClienteView {
    
    private ClienteController controller;
    private ClienteTableComboModel tableModel;
    private ClienteViewImplInternal panelCliente;

    /**
     * Creates new form ClienteViewImpl
     */
    public ClienteViewImpl() {
        tableModel = ClienteTableComboModel.getInstance();
        initComponents();
        
        panelCliente = new ClienteViewImplInternal(this);
        jPanelCliente.add(panelCliente);
    }
    
    @Override
    public ClienteController getController() {
        return controller;
    }

    @Override
    public void setController(ClienteController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCliente.setLayout(new javax.swing.BoxLayout(jPanelCliente, javax.swing.BoxLayout.LINE_AXIS));

        jTableClientes.setModel(tableModel);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        ClienteTableComboModel ctm = (ClienteTableComboModel) this.jTableClientes.getModel();
        Cliente cliente = ctm.getCliente(this.jTableClientes.getSelectedRow());
        
        panelCliente.setCliente(cliente);
    }//GEN-LAST:event_jTableClientesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables

    protected void fireCrearClienteGesture(String DNI, String nombre, String direccion) {
        controller.crearClienteGesture(DNI, nombre, direccion);
    }
    
    protected void fireModificarClienteGesture(String DNI, String nombre, String direccion) {
        controller.modificarClienteGesture(DNI, nombre, direccion);
    }
    
    protected void fireEliminarClienteGesture(String DNI) {
        controller.eliminarClienteGesture(DNI);
    }

    @Override
    public void dataModelChanged() {
        tableModel.setClientes(controller.listarClientesGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                dataModelChanged();
            }
        });
    }
      
}
