
package vista.cliente;

import controlador.ClienteController;
import controlador.MetodoPagoController;
import modelo.entidades.Cliente;
import modelo.entidades.MetodoPago;
import vista.metodo_pago.MetodoPagoModel;

public class ClienteViewImpl extends javax.swing.JPanel implements ClienteView {
    
    private ClienteController cController;
    private MetodoPagoController mController;
    private ClienteTableComboModel tableClienteModel;
    private MetodoPagoModel comboMetodoPago;
    private ClienteViewImplInternal panelCliente;

    public ClienteViewImpl() {
        tableClienteModel = ClienteTableComboModel.getInstance();
        comboMetodoPago = new MetodoPagoModel();
        initComponents();
        
        panelCliente = new ClienteViewImplInternal(this);
        jPanelCliente.add(panelCliente);
    }
    
    @Override
    public ClienteController getcController() {
        return cController;
    }

    @Override
    public void setcController(ClienteController cController) {
        this.cController = cController;
    }

    @Override
    public MetodoPagoModel getComboMetodoPago() {
        return comboMetodoPago;
    }

    @Override
    public MetodoPagoController getmController() {
        return mController;
    }

    @Override
    public void setmController(MetodoPagoController mController) {
        this.mController = mController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(450, 500));

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCliente.setPreferredSize(new java.awt.Dimension(450, 300));
        jPanelCliente.setLayout(new javax.swing.BoxLayout(jPanelCliente, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 400));

        jTableClientes.setModel(tableClienteModel);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        ClienteTableComboModel ctm = (ClienteTableComboModel) this.jTableClientes.getModel();
        Cliente cliente = ctm.getCliente(this.jTableClientes.getSelectedRow());
        
        panelCliente.setCliente(cliente);
    }//GEN-LAST:event_jTableClientesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables

    protected void fireCrearClienteGesture(String DNI, String nombre, String direccion, MetodoPago metodoPago) {
        cController.crearClienteGesture(DNI, nombre, direccion, metodoPago);
    }
    
    protected void fireModificarClienteGesture(String DNI, String nombre, String direccion, MetodoPago metodoPago) {
        cController.modificarClienteGesture(DNI, nombre, direccion, metodoPago);
    }
    
    protected void fireEliminarClienteGesture(String DNI) {
        cController.eliminarClienteGesture(DNI);
    }

    @Override
    public void dataModelChanged() {
        comboMetodoPago.setMetodos(mController.listarMetodosGesture());
        tableClienteModel.setClientes(cController.listarClientesGesture());
    }
    
    @Override
    public void display() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                dataModelChanged();
            }
        });
    }
      
}
